id: ID9539B46
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T02:40:20+00:00'
last_modified: '2022-06-08T05:28:34.718983+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12196
  title: རྫོགས་ཆེན་དགོན་པའི་ཕུར་ཆེན་གྱི་འདོན་ཆའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4220':
      image_group_id: I1KG12294
      title: ''
      total_pages: 478
      order: 1
      base_file: 4220.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
